name: RUBY
categories:
  - infrastructure
description: The Decentralized Privacy-Centric Protocol for Web3
product_readiness: testnet, January 2023
links:
  web: https://www.ruby.xyz
  github: https://github.com/Ruby-Protocol
have_token: true
token:
  symbol: RUBY
