name: ZeroPool
categories:
  - infrastructure
description: >-
  Is fully private multi-blockchain solution. Low transaction fees, atomic swaps
  and common anonymity set.
product_readiness: mainnet beta
links:
  web: https://zeropool.network/#rec246911850
