name: Masq
categories:
  - infrastructure
description: >-
  Meet MASQ, the dMeshVPN, browser, dAppStore, protocol, and earning ecosystem
  that makes living in Web3 anonymous and private
product_readiness: TBD
links:
  web: https://masq.ai
  github: https://github.com/MASQ-Project
