name: Haven Protocol
categories:
  - infrastructure
description: The world’s only network of private stable assets
product_readiness: live
links:
  web: https://havenprotocol.org
  github: https://github.com/haven-protocol-org
have_token: true
token:
  symbol: XHV
