name: Anytype
categories:
  - infrastructure
description: The digital assets and communities you create are truly yours.
product_readiness: TBD
links:
  web: https://anytype.io/en
  github: https://github.com/anytypeio
